[package]
name = "health_tracker"
version = "1.0.0"
authors = ["Health Tracker Team"]

[addresses]
health_tracker = "_"

[dev-addresses]
health_tracker = "0x42"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies] 